### PR TITLE
Support sylius 1.5

### LINKED ISSUE #256: Upgrade to sylius/sylius:~1.5.0
Is it possible to migrate this plugin to `sylius/sylius:~1.5.0` dependency for this plugin and maybe others ? Thanks !!

### PR DESCRIPTION
**Pull request by Prometee**
| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #256
| License         | MIT

### CODE REVIEW

**Comment by kubaceg** [comment]
So tests are green, when this PR will be merged? Or maybe update requires more work?

**Comment by Prometee** [comment]
@bitbager I just quickly test it and it works with no errors, but there is some deprecate log message for a while with the package `friendsofsymfony/ckeditor-bundle`, maybe it's time to upgrade the used version : https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/UPGRADE-2.0.md

**Comment by bitbager** [comment]
Thanks!

**Comment by kubaceg** [comment]
Will you publish a new version with this changes? Also there should be `~1.4.0|~1.5.0` than change will be backwards compatible.

**Pull request merged**
