### PR TITLE
provided ability for twig media tag to add optional template file string

### PR DESCRIPTION
**Pull request by porl**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | 
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by porl** [comment]
Not sure if the test for null !== $template was strictly necessary

**Comment by leszczuu** [comment]
Provide usage example, please.

**Comment by porl** [comment]
In my blocks/pages, I sometimes need to reference media files (usually images) but have them presented in a specific way. So In my block or template I would have:

```
{{ bitbag_cms_render_media('screenshot1', media/screenshot-card.html.twig) }}
{{ bitbag_cms_render_media('screenshot2', media/screenshot-card.html.twig) }}
{{ bitbag_cms_render_media('screenshot3', media/screenshot-card.html.twig) }}
{{ bitbag_cms_render_media('screenshot4', media/screenshot-card.html.twig) }}
```
instead of something like:

```
<div class="screenshot-card">
    {{ bitbag_cms_render_media('screenshot1') }}
</div>
<div class="screenshot-card">
    {{ bitbag_cms_render_media('screenshot2') }}
</div>
<div class="screenshot-card">
    {{ bitbag_cms_render_media('screenshot3') }}
</div>
<div class="screenshot-card">
    {{ bitbag_cms_render_media('screenshot4') }}
</div>
```
which is much easier to get messy (especially if an end-user is modifying page parts).

**Comment by porl** [comment]
This also brings the media render extension more into line with how the block render extension works.

**Review by leszczuu — APPROVED** [review]

**Comment by MacBalc** [comment]
It seems like some changes had been made in RenderMediaExtension that already solved issue this PR is trying to solve. Due to that closing.

**Pull request closed without merging**
