### PR TITLE
Test in CI against several combinations of dependencies

### PR DESCRIPTION
**Pull request by stefandoorn**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by bitbager** [comment]
Hi Stefan! Can I ask you to fix the build? 

Btw, @patrick477 is our CMS master at this moment. He will review all PRs and take care of CR and Q&A 🙂

**Comment by stefandoorn** [comment]
Yeah, it seems a bit more complicated than I can handle in the next days. So, feel free to take over @patrick477 if you want to have it soon.

**Comment by bitbager** [comment]
Can I ask you to merge current codebase with your fork? We will see if it passes now 🙂

**Comment by bitbager** [comment]
Already fixed on master.

**Comment by stefandoorn** [comment]
Thanks :)

**Comment by stefandoorn** [comment]
Might be interesting to also test against different Sylius versions.

**Comment by bitbager** [comment]
It won't be possible due to different Gulp configurations across Sylius versions.

**Pull request closed without merging**
