### PR TITLE
travis Sylius multi versions

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

Added a matrix to Travis for test the previous (and current) versions of Sylius.
Currently, tests are only run on Sylius 1.6.1.

### CODE REVIEW

**Comment by oallain** [comment]
Hello @bitbager 
Scrutinizer seems to have issues with the amount of dependencies. Maybe we should exclude some or maybe we can even exclude that whole step? Alternative is to remove Scrutinizer, as we have some other quality tools already.

**Comment by oallain** [comment]
Ping @BitBagCommerce @bitbager

**Comment by patrick477** [comment]
thanks :) scrutinizer we will check

**Comment by patrick477** [comment]
for the scrutinizer to end successfully, just add this config https://github.com/BitBagCommerce/SyliusCmsPlugin/commit/63f34720d1d427867a1d5deb972fe29070f2abff

**Pull request merged**
