### PR TITLE
Fixed channel, section and product option for fixtures

### PR DESCRIPTION
**Pull request by Peteck**
Don't really got much to say about this commit. I updated needed fixtures to use the assigners.

| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | Yes. Products is no longer an integer option but an array option
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by Peteck** [comment]
I have not run into a scenario yet where I need it, but I just think it a great feature to add allowing the user to have the flexibility to chose specific products.

I can't really find a way from the documentation of the config definitions: https://symfony.com/doc/current/components/config/definition.html

We can make a way where you could put an integer into the array and it would do the same functionality as before? But this would ofcourse still break the enviroment.

**Comment by bitbager** [comment]
In this case, it'll break our current feature and I simply cannot let it happen. It, of course, makes sense to have such a feature. I think we can either add it as a secondary option or customize the current association or provide a new configuration field. 

I am leaving this PR as opened. We will customize it once we have time but if you need it right now, we will appreciate a PR 😄

**Comment by Peteck** [comment]
Now fixtures for blocks and pages again support the old `products` integer attribute.

**Comment by bitbager** [comment]
Thank you!

**Pull request merged**
